/* AUTO GENERATED SQUIRE_CORE BINDINGS DO NOT MODIFY BY HAND. */

#pragma once

/* Generated with cbindgen:0.24.3 */

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <cassert>
#define SQUIRE_CORE

namespace squire_core {

/**
 * The length of a hyphenated [`Uuid`] string.
 *
 * [`Uuid`]: ../struct.Uuid.html
 */
constexpr static const size_t sc_Hyphenated_LENGTH = 36;

} // namespace squire_core

/* AUTO GENERATED SQUIRE_CORE BINDINGS DO NOT MODIFY BY HAND */
