[package]
name = "squire_lib"
version = "0.1.0-pre-alpha.1"
edition = "2021"
license = "GPL-3.0"
authors = ["TylerBloom <tylerbloom2222@gmail.com>"]

[lib]
crate-type = ["lib", "staticlib"]

[features]
default = ["deck_sites"]
#default = ["ffi", "mtgjson/deck_sites"]
deck_sites = ["mtgjson/deck_sites"]
ffi = ["cbindgen", "libc"]
wasm = ["chrono/wasmbind"]

[dependencies]
#In-house deps
cycle_map = { version = "0.1.1", features = ["serde"] }
mtgjson = { git = "https://github.com/TylerBloom/mtgjson-rust-sdk", rev="864d71022fd285defb371626e06d6de7c7119f45", default-features = false }
# mtgjson = { path = "../mtgjson-rust-sdk", features = ["deck_sites"] }
lazy_static = "1.4.0"

uuid = { version = "1.1", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.68" }
once_cell = { version = "1.8.0" }
dashmap = { version = "5.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }

libc = { version = "0.2", optional = true }

[build-dependencies]
cbindgen = { version = "0.20.0", optional = true}
