name: SquireCore CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code_cleaniness_checks:
    name: Formatting Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [nightly]
        os: [ubuntu-latest]
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt
          targets: wasm32-unknown-unknown
      - uses: actions/checkout@v4
      - run: cargo fmt --check --package squire_lib
      - run: cargo fmt --check --package squire_sdk
      - run: cargo fmt --check --package squire_web
      - run: cargo fmt --check --package squire_core
