name: Squire Coverage

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          targets: wasm32-unknown-unknown
      - name: Fetch Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - name: Fetch and run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
            version: '0.25.1'
            args: '--verbose --all-features --workspace --timeout 120'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
